name: CI

on:
    push:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
                cache: 'pip'
            - name: Create virtual environment
              run: python3 -m venv --upgrade-deps .venv

            - name: Install project dependencies
              run: .venv/bin/pip install .[dev]

            - name: Install playwright browsers
              run: .venv/bin/playwright install --with-deps chromium

            - name: Run Django tests
              run: make test
