name: CI

on:
    push:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
                cache: 'pip'
            - name: Install project dependencies
              run: pip install -r requirements.txt
            - name: Run Django tests
              run: python manage.py test
